kind: pipeline
name: default

steps:
  - name: install-dependancies
    image: node:alpine
    commands:
      - yarn install
      - yarn test

  - name: node-10
    image: node:10-alpine
    commands:
      - yarn test
    depends_on:
      - install-dependancies

  - name: node-11
    image: node:11-alpine
    commands:
      - yarn test
    depends_on:
      - install-dependancies

  - name: node-12
    image: node:12-alpine
    commands:
      - yarn test
    depends_on:
      - install-dependancies

  - name: node-13
    image: node:12-alpine
    commands:
      - yarn test
    depends_on:
      - install-dependancies

  - name: coverage-build
    image: node:alpine
    commands:
      - yarn test:coverage
    depends_on:
      - install-dependancies      

  - name: coverage-report
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
    depends_on:
      - install-dependancies
      - node-10
      - node-11
      - node-12
      - node-13
      - coverage-build
